# Generated by Django 5.1.5 on 2025-02-06 13:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(default='Yaounde', max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('lieu', models.TextField()),
                ('nombres_de_places', models.IntegerField(blank=True, null=True)),
                ('rempli', models.BooleanField(default=False)),
                ('prix', models.FloatField(default=0)),
                ('entree_gratuit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Billets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paye', models.DateField(default=datetime.date.today)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evenement')),
            ],
        ),
    ]
