# Generated by Django 5.1.5 on 2025-02-11 09:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(choices=[('marriage', 'Marriage'), ('seminar', 'Seminaire'), ('workshop', 'Atelier'), ('meeting', 'Meeting')], default='marriage', max_length=20),
        ),
        migrations.AddField(
            model_name='evenement',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'organisateur"),
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_heure_debut',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Debut (Date & heure)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_heure_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin (Date & heure)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisateur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('pres', 'Presentiel'), ('online', 'En ligne')], default='pres', max_length=10),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('rejected', 'Rejetée'), ('accepted', 'Accepté')], max_length=15)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evenement')),
            ],
        ),
    ]
