# Generated by Django 5.1.5 on 2025-02-12 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_evenement_categorie_evenement_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_heure_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Debut (Date & heure)'),
        ),
    ]
