# Generated by Django 5.1.5 on 2025-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_evenement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='invitation_email_received',
            field=models.BooleanField(null=True),
        ),
    ]
