# Generated by Django 5.1.5 on 2025-02-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_participant_invitation_email_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='invitation_email_received',
            new_name='invitation_successful',
        ),
    ]
