# Generated by Django 5.1.5 on 2025-02-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_invitation_email_received_participant_invitation_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('rejected', 'Rejetée'), ('accepted', 'Accepté')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye_avec_succes', models.BooleanField(default=False)),
                ('heure_denvoi', models.DateTimeField(auto_now_add=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notification')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
            ],
        ),
    ]
